aliases:
    apply-macOS-W.local: nix run --impure home-manager/master -- -b bak switch --flake .#zerodeth@macOS-W.local
    fleeks: cd ~/.local/share/fleek
    pinentry-mac: ~/.nix-profile/Applications/pinentry-mac.app/Contents/MacOS/pinentry-mac
allow_broken: true
auto_gc: false
bling: high
blocklist:
    - starship
    - eza
    - bat
    - atuin
    - zoxide
    - direnv
    - neovim
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: true
    autopush: true
    enabled: true
min_version: ""
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - gtop
    - nodejs-18_x
    - yarn
    - go
    - gopls
    - duf
    - ctop
    - kitty
    - git
    - htop
    - glab
    - fzf
    - ripgrep
    - vscode
    - lazygit
    - jq
    - yq-go
    - neofetch
    - btop
    - cheat
    - gnupg
    - pinentry_mac
    - python3
    - pre-commit
    - chezmoi
    - shellcheck
    - cachix
    - fish
    - thefuck
    - byobu
    - docker
    - colima
    - alacritty
    - iterm2
    - chatgpt-cli
    - lima
    - tmux
    - tree
    - tree-sitter
    - nix-index
    - topgrade
    - trash-cli
    - wezterm
    - devbox
    - prettyping
    - fh
    - colmena
    - arkade
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.gnupg
    - /opt/homebrew/bin
    - /opt/homebrew/sbin
programs:
    - dircolors
    - eza
    - bat
    - atuin
    - zoxide
    - direnv
    - neovim
    - zsh.oh-my-zsh
    - starship
    - gpg
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: macOS-0.local
      os: darwin
      user:
        email: sherif@abdalla.uk
        name: Sherif Abdalla
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: zerodeth
      username: zerodeth
    - arch: aarch64
      home: ""
      hostname: macOS-W.local
      os: darwin
      user:
        email: sherif@abdalla.uk
        name: Sherif Abdalla
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: zerodeth
      username: zerodeth
track: nixos-unstable
unfree: true
users:
    - email: sherif@abdalla.uk
      name: Sherif Abdalla
      ssh_private_key_file: ~/.ssh/id_ed25519
      ssh_public_key_file: ~/.ssh/id_ed25519.pub
      username: zerodeth
