---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://docs.gitguardian.com/ggshield-docs/integrations/git-hooks/pre-commit

ci:
    autofix_prs: true
    skip:
        - ggshield

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.1
      hooks:
          - id: prettier
            files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
    # - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    #   rev: v0.1.0
    #   hooks:
    #       - id: dockerfilelint
    # - repo: https://github.com/sirosen/check-jsonschema
    #   rev: 0.10.0
    #   hooks:
    #       - id: check-github-actions
    #       - id: check-github-workflows
    # - repo: https://github.com/shellcheck-py/shellcheck-py
    #   rev: v0.8.0.3
    #   hooks:
    #       - id: shellcheck
    # - repo: https://github.com/gitguardian/ggshield
    #   rev: v1.14.5
    #   hooks:
    #     - id: ggshield
    #       language_version: python3
    #       stages: [commit]
